export const projectOptions: string[] = [
  "AD Data Update",
  "Attending External Meetings",
  "Attending Internal Meetings",
  "Attending Vendor Meetings",
  "GCIO's Office Tasks",
  "HR & Admin Tasks",
  "Hyperconverged Infrastructure",
  "Infrastructure Task Management",
  "IT Application Tasks",
  "IT End User Support",
  "IT Portfolio Tasks",
  "IT Security Tasks",
  "NetOps Task Management",
  "Other Operational Tasks",
  "Other Project/Initiative Tasks",
  "Responding to Emails",
  "SAP - DCP Production Support",
  "SAP - DCP S4H Technical Upgrade Project",
  "SAP - Foods DFM carve out",
  "SAP - Foods Production Support",
  "SAP - Foods S4H Technical upgrade",
  "SAP Analytics - Custom reports",
  "SAP DFL support",
  "SAP Fiori Apps implementation",
  "SAP GRC Implementation",
  "SAP SuccessFactors implementation",
  "Server Ops Task Management",
  "Service Desk Ticket Management",
  "Service Management Tasks",
  "Troubleshooting",
]

export const locationOptions: string[] = [
  "HQ",
  "Remote",
  "Obajana",
  "Ibese",
  "Gboko",
  "NASCON",
  "DSR",
  "Agrosacks",
  "Pan Africa",
  "Work from Home",
  "Holiday / Leave",
];

export const taskOptions: string[] = [
  "INC#",
  "CHN#",
  "CHN#",
  "Admin",
  "S4H Mock1",
  "S4H Mock2",
  "S4H Mock3",
  "S4H Pre Prod",
  "S4H Prod",
  "BPC",
  "SuccessFactors",
  "Cement Data Purging",
  "Weighbridge",
  "SolMan",
  "DFM carve out",
  "Others",
]

export const rowData = [
  {Project: "IT End User Support", Location: "Remote", FreshService: "35000", "Task":"SuccessFactors" },
  {Project: "IT End User Support", Location: "Obajana", FreshService: "32000", "Task":"SuccessFactors"},
  {Project: "Troubleshooting", Location: "Ibese", FreshService: "72000", "Task":"Weighbridge"}
];